### ISSUE TITLE
Project doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [rvaser/bioparser#10]
A C++ header-only library should install its headers.

**Comment by rvaser** [comment]
I am not sure how to properly install an interface library with cmake, i.e. creating an object which would would be linked with zlib.

**Comment by yurivict** [comment]
Special cmake file needs to accompany it.
I've never did this myself, but I know this is possible.

For example, ```dune-common``` https://gitlab.dune-project.org/core/dune-common installs cmake scripts that make projects that use it link to particular libraries.

**Comment by rvaser** [comment]
Will have a look, thank you!

**Comment by rvaser** [comment]
I have managed to make install targets and create a package. Sorry for the delay.
