### ISSUE TITLE
How to run the test suite

### ISSUE THREAD

**Issue by tillea** [rvaser/bioparser#2]
Hi,
I intend to create an official Debian package from bioparser.  To make sure that all works correctly I'd like to run the provided test.  Unfortunately I'm not that familiar with googletest.  What I tried is `cmake .` which created a ''Makefile''.  But this does not feature any test target.  Please add the steps users need to do to your documentation.
Kind regards and thank you, Andreas.

**Comment by rvaser** [comment]
Hello Andreas,
you have to run `git submodule update --init`, `cmake -Dbioparser_build_tests=ON .` and `make`. I'll update the README over the weekend.

Best regards,
Robert

**Comment by rvaser** [comment]
I have updated the README :)

Best regards,
Robert
