### ISSUE TITLE
Full name not stored when parsing fastq

### ISSUE THREAD

**Issue by bsipos** [rvaser/bioparser#3]
Hello,

It seems that bioparser does not store the full read name when parsing fastq (if the name is very long). Is there a way to achieve that behavior?

Thanks,
Botond

**Comment by rvaser** [comment]
Hi Botond,
I have a predefined maximum of 1024 characters for sequence names because I thought that should be more than enough. How long are the ones in your data set?

Best regards,
Robert

**Comment by bsipos** [comment]
Actually I realized that the problem is not the length, but that it cuts it off at a space. I guess that is not the name any more but the description, however I would like to keep the full fastq header.

Botond

**Comment by rvaser** [comment]
Are you using bioparser directly or through some of the other projects?

**Comment by bsipos** [comment]
I am using bioparser directly in one of my projects.

**Comment by rvaser** [comment]
Would a separate branch with the desired behavior be sufficient at this time? I'll add it to master later when I update other repositories.

**Comment by bsipos** [comment]
Yes, that would work for me!

**Comment by rvaser** [comment]
Checkout branch temp :)

**Comment by bsipos** [comment]
Thanks for the quick fix!

Botond

**Comment by rvaser** [comment]
@bsipos I have enabled full headers in master branch by adding an optional argument to the parse function. May I delete the `temp` branch?

**Comment by bsipos** [comment]
Sure! Thanks!
