### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by tillea** [rvaser/bioparser#4]
Hi,
I'm trying to update the Debian package of spoa to the latest version.  Unfortunately spoa is simply using a Git submodule to the latest commit which is not compatible with Debian policy.  We need to package libraries separately to avoid code duplication.  While I simply could package the latest commit of bioparser this is not the prefered way of maintenance.  We rather prefer tagged releases to know whether upstream is considering some commit as ready production  in contrast to a random development commit.
Kind regards, Andreas.

**Comment by rvaser** [comment]
Hi Andreas,
will sort it out :)

Thanks and best regards,
Robert

**Comment by rvaser** [comment]
Should be sorted out now. If not, let me know.
